import HyperLink from '../../../components/Basic/HyerLink.tsx';
import ShowMoreText from 'react-show-more-text';
import { Bot } from 'lucide-react';
import { Tooltip } from 'react-tooltip';
import { ThumbsDown, ThumbsUp } from '@phosphor-icons/react';
import Modal from '../../../components/Modal/Modal.tsx';
import CommentForm from '../../../components/Forms/CommentForm.tsx';
import { Row } from '@tanstack/react-table';
import { TriggerFinal } from '../../../types/TriggerFinal.ts';
import usePutComment from '../../../hooks/interface/usePutComment.ts';
import { useContext, useState } from 'react';
import { AuthContext } from '../../../components/AuthWrapper.tsx';
import { useQueryClient } from '@tanstack/react-query';

export default function TriggerNoteDetail({ row }: { row: Row<TriggerFinal> }) {
  const { route } = useContext(AuthContext);
  const [showModal, setShowModal] = useState(false);
  const queryClient = useQueryClient();
  const putComment = usePutComment(route, queryClient);
  if (row.getValue('progress_note_id') === null)
    return (
      <div className="bg-slate-50 dark:bg-slate-900 px-4 text-sm py-4 flex flex-wrap">
        <div className="basis-1/2 border-r border-stroke pr-10">
          <div>
            <span className="font-bold">Patient Name:</span>
            {row.original.upstream === 'MTX' ? (
              <HyperLink
                tooltip_content="View Patient in MaxtrixCare"
                href={`https://clearviewhcm.matrixcare.com/core/selectResident.action?residentID=${row.original.patient_id}`}
              >
                {row.getValue('patient_name')}
              </HyperLink>
            ) : row.original.upstream === 'PCC' ? (
              <HyperLink
                tooltip_content="View Patient in PCC"
                href={`https://www19.pointclickcare.com/admin/client/clientlist.jsp?ESOLtabtype=C&ESOLglobalclientsearch=Y&ESOLclientid=${row.original.patient_id}&ESOLfacid=${row.original.internal_facility_id.split('_').pop()}&ESOLsave=P`}
              >
                {row.getValue('patient_name')}
              </HyperLink>
            ) : (
              <p>{row.getValue('patient_name')}</p>
            )}
          </div>
          <div className="mt-2.5">
            <span className="font-bold">Patient ID: </span>
            <p>{row.original.patient_id}</p>
          </div>
        </div>
        <div className="basis-1/2 pl-10">
          <div>
            <span className="font-bold">Facility Name:</span>
            <p>{row.getValue('facility_name')}</p>
          </div>
        </div>
        <table className="basis-full mt-7.5 border-stroke border-t border-spacing-y-2.5 border-separate">
          <thead>
            <tr>
              <th className="text-left w-4/12">
                <div className="flex gap-1.5">
                  <p>Trigger</p>
                  {/*<Bot*/}
                  {/*  data-tooltip-id="bot-tooltip"*/}
                  {/*  data-tooltip-content="Trigger generated by AI from Progress Note"*/}
                  {/*  className="size-5 block focus:outline-none"*/}
                  {/*/>*/}
                  {/*<Tooltip id="bot-tooltip" />*/}
                </div>
              </th>
              <th className="text-left pr-10 w-8/12">
                <div className="flex gap-1.5">
                  <p>Explanations</p>
                  {/*<Bot*/}
                  {/*  data-tooltip-id="bot-tooltip"*/}
                  {/*  data-tooltip-content="Explanation generated by AI from Progress Note"*/}
                  {/*  className="size-5 block focus:outline-none"*/}
                  {/*/>*/}
                  {/*<Tooltip id="bot-tooltip" />*/}
                </div>
              </th>
            </tr>
          </thead>
          <tbody>
            {row.original.trigger_words.map(({ trigger_word, summary }) => (
              <tr key={row.id + trigger_word}>
                <td className="whitespace-nowrap align-top flex items-center flex-nowrap">
                  {trigger_word}
                </td>
                <td className="pr-10">
                  <ShowMoreText
                    className="whitespace-pre-line"
                    anchorClass="text-primary cursor-pointer block dark:text-secondary"
                  >
                    {summary}
                  </ShowMoreText>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    );

  return (
    <div className="bg-slate-50 dark:bg-slate-900 px-4 text-sm py-4 flex flex-wrap">
      <div className="basis-1/2 border-r border-stroke pr-10">
        <div>
          <span className="font-bold">Progress Note:</span>
          <ShowMoreText
            className="whitespace-pre-line"
            anchorClass="text-primary cursor-pointer block dark:text-secondary "
          >
            <p>{row.getValue('progress_note')}</p>
          </ShowMoreText>
        </div>
        <div className="mt-2.5">
          <span className="font-bold"> Progress Note ID:</span>
          <p>{row.getValue('progress_note_id')}</p>
        </div>
        <div className="mt-2.5">
          <span className="font-bold"> Created By:</span>
          <p>{row.getValue('created_by')}</p>
        </div>
        <div className="mt-2.5">
          <span className="font-bold">Created Date: </span>
          <p>
            {new Date(row.getValue('created_date')).toLocaleDateString()}{' '}
            {new Date(row.getValue('created_date')).toLocaleTimeString(
              navigator.language,
              {
                hour: '2-digit',
                minute: '2-digit',
              },
            )}
          </p>
        </div>
      </div>
      <div className="basis-1/2 pl-10">
        <div>
          <span className="font-bold">Patient Name:</span>
          {row.original.upstream === 'MTX' ? (
            <HyperLink
              tooltip_content="View Patient in MaxtrixCare"
              href={`https://clearviewhcm.matrixcare.com/core/selectResident.action?residentID=${row.original.patient_id}`}
            >
              {row.getValue('patient_name')}
            </HyperLink>
          ) : row.original.upstream === 'PCC' ? (
            <HyperLink
              tooltip_content="View Patient in PCC"
              href={`https://www19.pointclickcare.com/admin/client/clientlist.jsp?ESOLtabtype=C&ESOLglobalclientsearch=Y&ESOLclientid=${row.original.patient_id}&ESOLfacid=${row.original.internal_facility_id.split('_').pop()}&ESOLsave=P`}
            >
              {row.getValue('patient_name')}
            </HyperLink>
          ) : (
            <p>{row.getValue('patient_name')}</p>
          )}
        </div>
        <div className="mt-2.5">
          <span className="font-bold">Patient ID: </span>
          <p>{row.original.patient_id}</p>
        </div>
        <div className="mt-2.5">
          <span className="font-bold">Facility Name:</span>
          <p>{row.getValue('facility_name')}</p>
        </div>
        <div className="mt-2.5">
          <span className="font-bold">Last Revision By:</span>
          <p>{row.getValue('revision_by')}</p>
        </div>
        <div className="mt-2.5">
          <span className="font-bold">Last Revision Date:</span>
          <p>
            {new Date(row.getValue('revision_date')).toLocaleDateString()}{' '}
            {new Date(row.getValue('revision_date')).toLocaleTimeString(
              navigator.language,
              {
                hour: '2-digit',
                minute: '2-digit',
              },
            )}
          </p>
        </div>
      </div>
      <table className="basis-full mt-7.5 border-stroke border-t border-spacing-y-2.5 border-separate">
        <thead>
          <tr>
            <th className="text-left w-2/12">
              <div className="flex gap-1.5">
                <p>Trigger</p>
                <Bot
                  data-tooltip-id="bot-tooltip"
                  data-tooltip-content="Trigger generated by AI from Progress Note"
                  className="size-5 block focus:outline-none"
                />
                <Tooltip id="bot-tooltip" />
              </div>
            </th>
            <th className="text-left pr-10 w-6/12">
              <div className="flex gap-1.5">
                <p>Explanations</p>
                <Bot
                  data-tooltip-id="bot-tooltip"
                  data-tooltip-content="Explanation generated by AI from Progress Note"
                  className="size-5 block focus:outline-none"
                />
                <Tooltip id="bot-tooltip" />
              </div>
            </th>
            <th className="text-left  w-2/12">
              <p>Review</p>
            </th>
            <th className="text-left w-2/12">
              <p>Actions</p>
            </th>
          </tr>
        </thead>
        <tbody>
          {row.original.trigger_words.map(
            ({ trigger_word, is_thumb_up, summary, comment, event_ids }) => (
              <tr key={row.id + trigger_word}>
                <td className="whitespace-nowrap align-top flex items-center flex-nowrap">
                  {trigger_word}
                </td>
                <td className="pr-10">
                  <ShowMoreText
                    className="whitespace-pre-line"
                    anchorClass="text-primary cursor-pointer block dark:text-secondary"
                  >
                    {summary}
                  </ShowMoreText>
                </td>
                <td className=" align-top	">
                  <div className=" flex items-center flex-nowrap gap-2">
                    {is_thumb_up ? (
                      <ThumbsUp
                        className="size-4 text-meta-3 cursor-pointer"
                        weight="fill"
                      />
                    ) : (
                      <ThumbsUp
                        className="size-4 cursor-pointer"
                        onClick={() =>
                          putComment.mutate({
                            progress_note_id: row.original.progress_note_id,
                            trigger_word: trigger_word,
                            comment: '',
                            is_thumb_up: true,
                          })
                        }
                      />
                    )}
                    {!is_thumb_up && comment !== null ? (
                      <Modal
                        isOpen={showModal}
                        setIsOpen={setShowModal}
                        classNameses={{
                          title: 'text-xl sm:text-2xl',
                        }}
                        title={'What is Going Wrong?'}
                        button={
                          <ThumbsDown
                            className="size-4 cursor-pointer text-meta-1"
                            weight="fill"
                          />
                        }
                      >
                        <CommentForm
                          comment={{
                            comment: comment || '',
                            trigger_word,
                            progress_note_id: row.original.progress_note_id,
                          }}
                          setIsOpen={setShowModal}
                        />
                      </Modal>
                    ) : (
                      <Modal
                        isOpen={showModal}
                        setIsOpen={setShowModal}
                        classNameses={{
                          title: 'text-xl sm:text-2xl',
                        }}
                        title={'What is Going Wrong?'}
                        button={
                          <ThumbsDown className="size-4 cursor-pointer" />
                        }
                      >
                        <CommentForm
                          comment={{
                            comment: comment || '',
                            trigger_word,
                            progress_note_id: row.original.progress_note_id,
                          }}
                          setIsOpen={setShowModal}
                        />
                      </Modal>
                    )}
                  </div>
                </td>
                <td className="align-top ">
                  {row.original.upstream === 'MTX' ? (
                    event_ids && event_ids.length > 0 ? (
                      event_ids.map((event_id) => (
                        <HyperLink
                          key={event_id}
                          href={`https://clearviewhcm.matrixcare.com/Zion?zionpagealias=EVENTVIEW&NSPID=${row.original.patient_id}&CHGPID=true&EVENTID=${event_id}&dashboardHomePage=true&OEType=Event&PATIENTID=${row.original.patient_id}`}
                        >
                          View the Event
                        </HyperLink>
                      ))
                    ) : trigger_word === 'Fall' ? (
                      <HyperLink
                        tooltip_content={'Create an Event in MatrixCare'}
                        href={`https://clearviewhcm.matrixcare.com/Zion?zionpagealias=EVENTCREATE&PATIENTID=${row.original.patient_id}&formId=944&categoryName=Safety%20Events&formDescription=Post+Fall+Event+v3`}
                      >
                        Create Event
                      </HyperLink>
                    ) : trigger_word === 'Wound/Ulcer' ? (
                      <HyperLink
                        tooltip_content={'Create an Event in MatrixCare'}
                        href={`https://clearviewhcm.matrixcare.com/Zion?zionpagealias=EVENTCREATE&PATIENTID=${row.original.patient_id}&formId=948&categoryName=Skin%20Integrity%20Events&formDescription=Wound+Other+Event`}
                      >
                        Create Event
                      </HyperLink>
                    ) : (
                      <HyperLink
                        tooltip_content={'Create an Event in MatrixCare'}
                        href={`https://clearviewhcm.matrixcare.com/Zion?zionpagealias=EVENTCREATE&PATIENTID=${row.original.patient_id}`}
                      >
                        Create Event
                      </HyperLink>
                    )
                  ) : (
                    row.original.upstream === 'PCC' && <p>Comming Soon</p>
                  )}
                </td>
              </tr>
            ),
          )}
        </tbody>
      </table>
    </div>
  );
}
