import { Bot } from 'lucide-react';
import { Tooltip } from 'react-tooltip';
import { ThumbsUp } from '@phosphor-icons/react';
import { ICD10 } from '../../types/MDSFinal.ts';

export default function MDSSuggestion({ icd10 }: { icd10: ICD10[] }) {
  return (
    <table className="basis-full mt-7.5 border-stroke border-t border-spacing-y-2.5 border-separate">
      <thead>
        <tr>
          <th className="text-left w-2/12">
            <div className="flex gap-1.5">
              <p>Potential ICD-10 Code</p>
              <Bot
                data-tooltip-id="bot-tooltip"
                data-tooltip-content="Trigger generated by AI from Progress Note"
                className="size-5 block focus:outline-none"
              />
              <Tooltip id="bot-tooltip" />
            </div>
          </th>
          <th className="text-left w-7/12">
            <div className="flex gap-1.5">
              <p>Progress Notes/Explanation</p>
              <Bot
                data-tooltip-id="bot-tooltip"
                data-tooltip-content="Explanation generated by AI from Progress Note"
                className="size-5 block focus:outline-none"
              />
              <Tooltip id="bot-tooltip" />
            </div>
          </th>

          <th className="text-left  w-1/12">
            <p>Review</p>
          </th>
          <th className="text-left w-2/12">
            <p>Actions</p>
          </th>
        </tr>
      </thead>
      <tbody>
        {icd10.map(({ icd10, progress_note, comment, is_thumb_up }) => (
          <tr key={icd10}>
            <td className="whitespace-nowrap align-top flex items-center flex-nowrap">
              {icd10}
            </td>
            <td className="pr-10">
              <p
                className="line-clamp-3"
                dangerouslySetInnerHTML={{
                  __html: progress_note
                    .map(({ progress_note }) => progress_note)
                    .join('<br />'),
                }}
              ></p>
            </td>
            <td className=" align-top	">
              <div className=" flex items-center flex-nowrap gap-2">
                {is_thumb_up ? (
                  <ThumbsUp
                    className="size-4 text-meta-3 cursor-pointer"
                    weight="fill"
                  />
                ) : (
                  <ThumbsUp
                    className="size-4 cursor-pointer"
                    // onClick={() =>
                    //   putComment.mutate({
                    //     progress_note_id: row.original.progress_note_id,
                    //     trigger_word: trigger_word,
                    //     comment: '',
                    //     is_thumb_up: true,
                    //   })
                    // }
                  />
                )}
                {/*{!is_thumb_up && comment !== null ? (*/}
                {/*  <Modal*/}
                {/*    isOpen={showModal}*/}
                {/*    setIsOpen={setShowModal}*/}
                {/*    classNameses={{*/}
                {/*      title: 'text-xl sm:text-2xl',*/}
                {/*    }}*/}
                {/*    title={'What is Going Wrong?'}*/}
                {/*    button={*/}
                {/*      <ThumbsDown*/}
                {/*        className="size-4 cursor-pointer text-meta-1"*/}
                {/*        weight="fill"*/}
                {/*      />*/}
                {/*    }*/}
                {/*  >*/}
                {/*    <CommentForm*/}
                {/*      comment={{*/}
                {/*        comment: comment || '',*/}
                {/*        trigger_word,*/}
                {/*        progress_note_id: row.original.progress_note_id,*/}
                {/*      }}*/}
                {/*      setIsOpen={setShowModal}*/}
                {/*    />*/}
                {/*  </Modal>*/}
                {/*) : (*/}
                {/*  <Modal*/}
                {/*    isOpen={showModal}*/}
                {/*    setIsOpen={setShowModal}*/}
                {/*    classNameses={{*/}
                {/*      title: 'text-xl sm:text-2xl',*/}
                {/*    }}*/}
                {/*    title={'What is Going Wrong?'}*/}
                {/*    button={*/}
                {/*      <ThumbsDown className="size-4 cursor-pointer" />*/}
                {/*    }*/}
                {/*  >*/}
                {/*    <CommentForm*/}
                {/*      comment={{*/}
                {/*        comment: comment || '',*/}
                {/*        trigger_word,*/}
                {/*        progress_note_id: row.original.progress_note_id,*/}
                {/*      }}*/}
                {/*      setIsOpen={setShowModal}*/}
                {/*    />*/}
                {/*  </Modal>*/}
                {/*)}*/}
              </div>
            </td>
            <td className="align-top ">
              <p>Comming Soon</p>
            </td>
          </tr>
        ))}
      </tbody>
    </table>
  );
}
